// "use client"
import Nav from '@/app/components/header/Nav/nav'
import Footer from './components/Footer/Footer';
import type { Metadata } from "next";
import './globals.css';
import './scrollbar.css'

export const metadata: Metadata = {
  title: "Arshia-Mansury",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='dark'>
        <div className='bg-white text-black dark:bg-black dark:text-white'>
          <Nav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
